name: gogoshop
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.1.0
  carousel_slider: ^4.2.1
  image_picker: ^1.0.7
  device_info_plus: ^10.0.1
  story_view: ^0.16.5
  flutter_chat_ui: ^1.6.12

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/catalog_icon/
    - assets/images/Navigatonbaricon/

  fonts:
    - family: Musio
      fonts:
        - asset: assets/fonts/Musio.otf
